# Generated by Django 4.2.1 on 2023-05-16 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Machine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hostname", models.CharField(max_length=200)),
                ("mac_address", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200)),
                ("comment", models.CharField(max_length=2000)),
                ("runtimer", models.DurationField(blank=True)),
                ("min_power", models.IntegerField(blank=True)),
                ("control_parameter", models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="MachineTimes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="machines.machine",
                    ),
                ),
            ],
        ),
    ]
