# Generated by Django 4.2.1 on 2023-05-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("machines", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="comment",
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name="machine",
            name="min_power",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="machine",
            name="runtimer",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
