# Generated by Django 4.2.1 on 2023-05-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("machines", "0002_alter_machine_comment_alter_machine_min_power_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
