# Generated by Django 5.0 on 2024-01-29 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0003_alter_machineconfig_machine'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ['pk'], 'verbose_name': 'Machine', 'verbose_name_plural': 'Machines'},
        ),
    ]
