# Generated by Django 5.0 on 2023-12-15 23:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_rfidinguser_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rfidinguser",
            name="username",
        ),
    ]
