# Generated by Django 5.0 on 2023-12-16 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_rfidinguser_managers_rfidinguser_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfidinguser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='rfidinguser',
            name='last_name',
        ),
    ]
