# Generated by Django 5.0 on 2023-12-16 03:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_rfidinguser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfidinguser',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('de', 'Deutsch')], default='en', max_length=10, verbose_name='Langauge'),
        ),
        migrations.AlterField(
            model_name='rfidinguser',
            name='page_length',
            field=models.IntegerField(default=50, help_text='Number of items to show per page', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)], verbose_name='Page Length'),
        ),
    ]
