# Generated by Django 5.1.1 on 2024-09-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_rfidinguser_theme_rfidinguser_theme_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rfidinguser",
            name="theme",
            field=models.CharField(
                choices=[
                    ("default", "Default (Blue)"),
                    ("purple", "Purple"),
                    ("red", "Red"),
                    ("orange", "Orange"),
                    ("yellow", "Yellow"),
                    ("green", "Green"),
                    ("pink", "Pink"),
                    ("teal", "Teal"),
                    ("cyan", "Cyan"),
                ],
                default="default",
                max_length=10,
            ),
        ),
    ]
