# Generated by Django 5.1.1 on 2024-10-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("access_log", "0003_alter_accesslog_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesslog",
            name="type",
            field=models.CharField(
                choices=[
                    ("booted", "Booted"),
                    ("enabled", "Enabled"),
                    ("disabled", "Disabled"),
                    ("registered", "Registered"),
                ],
                max_length=20,
            ),
        ),
    ]
