# Generated by Django 5.1.5 on 2025-02-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("access_log", "0004_alter_accesslog_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesslog",
            name="type",
            field=models.CharField(
                choices=[
                    ("booted", "Booted"),
                    ("enabled", "Enabled"),
                    ("disabled", "Disabled"),
                    ("unsuccessful", "Unsuccessful"),
                ],
                max_length=20,
            ),
        ),
    ]
