# Generated by Django 5.1.5 on 2025-03-15 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_log", "0005_alter_accesslog_type"),
        ("tokens", "0014_alter_token_options_alter_unknowntoken_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accesslog",
            options={
                "ordering": ("-timestamp",),
                "verbose_name": "Access Log",
                "verbose_name_plural": "Access Logs",
            },
        ),
        migrations.AlterField(
            model_name="accesslog",
            name="token",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tokens.token",
            ),
        ),
    ]
