# Generated by Django 6.0.7 on 2026-10-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_log', '0008_accesslog_unsuccessful_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='unsuccessful_reason',
            field=models.CharField(blank=True, choices=[('unknown_token', 'Unknown token'), ('inactive_token', 'Inactive token'), ('unknown_compartment', 'Unknown compartment'), ('lock_group', 'Machine is a lock group'), ('holiday', 'Restricted on holidays'), ('outside_hours', 'Outside of allowed times'), ('not_qualified', 'Not qualified'), ('qualification_blocked', 'Qualification blocked'), ('qualification_expired', 'Qualification expired'), ('maintenance', 'Machine in maintenance'), ('machine_blocked', 'Machine blocked'), ('space_closed', 'Space is closed'), ('internal_error', 'Internal error')], help_text="Why access was denied. Only set for 'unsuccessful' events.", max_length=32, null=True, verbose_name='Reason'),
        ),
    ]
