# Generated by Django 5.0 on 2023-12-16 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("machines", "0002_alter_machine_ip_address_alter_machinetimes_machine"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machineconfig",
            name="machine",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="config",
                to="machines.machine",
            ),
        ),
    ]
