# Generated by Django 5.1.1 on 2024-10-08 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0009_alter_machine_chip_alter_machine_completed_setup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MachineTimes',
            new_name='MachineTime',
        ),
    ]
