# Generated by Django 5.1.1 on 2024-12-10 21:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "machines",
            "0011_alter_machine_options_machine_access_control_module_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="machine",
            options={
                "ordering": ["pk"],
                "verbose_name": "Machine",
                "verbose_name_plural": "Machines",
            },
        ),
        migrations.AlterField(
            model_name="machine",
            name="access_control_module",
            field=models.IntegerField(
                choices=[(1, "RFID Reader"), (0, "None")], default=0
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="access_control_module_settings",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="machine",
            name="actor_module",
            field=models.IntegerField(
                choices=[
                    (3, "Lock"),
                    (2, "Relay with power meter"),
                    (0, "None"),
                    (1, "Relay"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="actor_module_settings",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="machine",
            name="status_display_module",
            field=models.IntegerField(
                choices=[
                    (0, "None"),
                    (4, "Single RGB LED"),
                    (1, "Onboard LED"),
                    (3, "Red/Green LED"),
                    (5, "RGB Ring LED"),
                    (2, "Double LEDs"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="status_display_module_settings",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
