# Generated by Django 5.1.1 on 2024-12-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("machines", "0012_alter_machine_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="access_control_module",
            field=models.IntegerField(
                choices=[(0, "None"), (1, "RFID Reader")], default=0
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="actor_module",
            field=models.IntegerField(
                choices=[
                    (0, "None"),
                    (1, "Relay"),
                    (2, "Relay with power meter"),
                    (3, "Lock"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="status_display_module",
            field=models.IntegerField(
                choices=[
                    (0, "None"),
                    (4, "Single RGB LED"),
                    (3, "Red/Green LED"),
                    (5, "RGB Ring LED"),
                    (2, "Double LEDs"),
                    (1, "Onboard LED"),
                ],
                default=0,
            ),
        ),
    ]
