# Generated by Django 5.1.2 on 2024-12-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machines", "0013_alter_machine_access_control_module_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="encryption_key",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="machine",
            name="access_control_module",
            field=models.IntegerField(
                choices=[(1, "RFID Reader"), (0, "None")], default=0
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="actor_module",
            field=models.IntegerField(
                choices=[
                    (1, "Relay"),
                    (3, "Lock"),
                    (2, "Relay with power meter"),
                    (0, "None"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="status_display_module",
            field=models.IntegerField(
                choices=[
                    (0, "None"),
                    (3, "Red/Green LED"),
                    (2, "Double LEDs"),
                    (5, "RGB Ring LED"),
                    (4, "Single RGB LED"),
                    (1, "Onboard LED"),
                ],
                default=0,
            ),
        ),
    ]
