# Generated by Django 5.1.5 on 2025-02-11 22:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("machines", "0014_machine_encryption_key_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MachineRegistrationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("mac_address", models.CharField(db_index=True, max_length=17)),
                ("hostname", models.CharField(max_length=100)),
                ("ip_address", models.GenericIPAddressField()),
                (
                    "chip",
                    models.CharField(
                        choices=[
                            ("esp32", "ESP32"),
                            ("esp8266", "ESP8266"),
                            ("esp32s2", "ESP32-S2"),
                            ("esp32c3", "ESP32-C3"),
                            ("esp32s3", "ESP32-S3"),
                        ],
                        default="esp32",
                        max_length=100,
                    ),
                ),
                (
                    "firmware_version",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
            options={
                "verbose_name": "Registration Request",
                "verbose_name_plural": "Registration Requests",
                "ordering": ["-created"],
            },
        ),
        migrations.AlterField(
            model_name="machine",
            name="actor_module",
            field=models.IntegerField(
                choices=[
                    (3, "Lock"),
                    (2, "Relay with power meter"),
                    (0, "None"),
                    (1, "Relay"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="chip",
            field=models.CharField(
                choices=[
                    ("esp32", "ESP32"),
                    ("esp8266", "ESP8266"),
                    ("esp32s2", "ESP32-S2"),
                    ("esp32c3", "ESP32-C3"),
                    ("esp32s3", "ESP32-S3"),
                ],
                default="esp32",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="status_display_module",
            field=models.IntegerField(
                choices=[
                    (4, "Single RGB LED"),
                    (1, "Onboard LED"),
                    (2, "Double LEDs"),
                    (3, "Red/Green LED"),
                    (0, "None"),
                    (5, "RGB Ring LED"),
                ],
                default=0,
            ),
        ),
    ]
