# Generated by Django 5.1.5 on 2025-02-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machines", "0015_machineregistrationrequest_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="machine",
            name="completed_setup",
        ),
        migrations.RemoveField(
            model_name="machineregistrationrequest",
            name="chip",
        ),
        migrations.RemoveField(
            model_name="machineregistrationrequest",
            name="firmware_version",
        ),
        migrations.AlterField(
            model_name="machine",
            name="access_control_module",
            field=models.IntegerField(
                choices=[(0, "None"), (1, "RFID Reader")], default=0
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="actor_module",
            field=models.IntegerField(
                choices=[
                    (1, "Relay"),
                    (2, "Relay with power meter"),
                    (0, "None"),
                    (3, "Lock"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="encryption_key",
            field=models.CharField(
                blank=True,
                help_text="32 character encryption key for secure communication with the machine.",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="status_display_module",
            field=models.IntegerField(
                choices=[
                    (4, "Single RGB LED"),
                    (0, "None"),
                    (1, "Onboard LED"),
                    (3, "Red/Green LED"),
                    (2, "Double LEDs"),
                    (5, "RGB Ring LED"),
                ],
                default=0,
            ),
        ),
    ]
