# Generated by Django 5.1.5 on 2025-02-19 16:03

from django.db import migrations, models
from datetime import timedelta

def migrate_runtimer(apps, schema_editor):
    Machine = apps.get_model("machines", "Machine")
    for machine in Machine.objects.all():
        machine.runtimer_new = timedelta(milliseconds=machine.runtimer)
        machine.save()


class Migration(migrations.Migration):
    dependencies = [
        ("machines", "0016_remove_machine_completed_setup_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="actor_module",
            field=models.IntegerField(
                choices=[
                    (0, "None"),
                    (1, "Relay"),
                    (2, "Relay with power meter"),
                    (3, "Lock"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="min_power",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="machine",
            name="runtimer_new",
            field=models.DurationField(default=timedelta(0)),
        ),
        migrations.RunPython(migrate_runtimer),
        migrations.RemoveField(model_name="machine", name="runtimer"),
        migrations.RenameField(
            model_name="machine",
            old_name="runtimer_new",
            new_name="runtimer",
        ),
        migrations.AlterField(
            model_name="machine",
            name="status_display_module",
            field=models.IntegerField(
                choices=[
                    (0, "None"),
                    (1, "Onboard LED"),
                    (2, "Double LEDs"),
                    (3, "Red/Green LED"),
                    (4, "Single RGB LED"),
                    (5, "RGB Ring LED"),
                ],
                default=0,
            ),
        ),
    ]
