# Generated by Django 5.1.5 on 2025-02-20 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0002_alter_location_options"),
        (
            "machines",
            "0017_alter_machine_actor_module_alter_machine_min_power_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="machines",
                to="locations.location",
            ),
        ),
    ]
