# Generated by Django 5.1.5 on 2025-02-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("machines", "0018_machine_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="display_power_consumption",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="machine",
            name="display_time_countdown",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="machine",
            name="link_relays",
            field=models.BooleanField(default=False),
        ),
    ]
