# Generated by Django 5.1.5 on 2025-02-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machines", "0019_machine_display_power_consumption_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="display_power_consumption",
            field=models.BooleanField(
                default=True,
                help_text="If the machine displays the power consumption when it is active.",
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="display_time_countdown",
            field=models.BooleanField(
                default=True,
                help_text="Whether the machine displays the time remaining until it locks again when it is unlocked but not active.",
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="link_relays",
            field=models.BooleanField(
                default=False,
                help_text="If set, the machine relays are linked and the secondary relay is activated together with the primary relay.",
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="min_power",
            field=models.IntegerField(
                default=10,
                help_text="Minimum power consumption in watts for the machine to be considered active.",
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="runtimer",
            field=models.DurationField(
                default=0,
                help_text="Time until the machine is locked again when it is not active.",
            ),
        ),
    ]
