# Generated by Django 5.1.5 on 2025-02-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("machines", "0020_alter_machine_display_power_consumption_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="machine",
            options={
                "ordering": ["name"],
                "verbose_name": "Machine",
                "verbose_name_plural": "Machines",
            },
        ),
        migrations.AlterField(
            model_name="machine",
            name="encryption_key",
            field=models.CharField(
                blank=True,
                help_text="32 character encryption key for secure communication with the machine.",
                max_length=64,
                null=True,
            ),
        ),
    ]
