# Generated by Django 5.1.5 on 2025-02-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machines", "0021_alter_machine_options_alter_machine_encryption_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="log_booted",
            field=models.BooleanField(default=True, help_text="Log boot events"),
        ),
        migrations.AddField(
            model_name="machine",
            name="log_disabled",
            field=models.BooleanField(
                default=False, help_text="Log when machine is disabled again"
            ),
        ),
        migrations.AddField(
            model_name="machine",
            name="log_enabled",
            field=models.BooleanField(
                default=True, help_text="Log successful unlock events"
            ),
        ),
        migrations.AddField(
            model_name="machine",
            name="log_unsuccessful",
            field=models.BooleanField(
                default=False, help_text="Log unsuccessful unlock attempts"
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="encryption_key",
            field=models.CharField(
                blank=True,
                help_text="64 character encryption key for secure communication with the machine.",
                max_length=64,
                null=True,
            ),
        ),
    ]
