# Generated by Django 5.1.5 on 2025-02-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("machines", "0022_machine_log_booted_machine_log_disabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="type",
            field=models.CharField(
                choices=[
                    ("primary", "Primary"),
                    ("secondary", "Secondary"),
                    ("lock", "Lock"),
                    ("lockbox", "Multiple Locks"),
                ],
                default="primary",
                max_length=100,
            ),
        ),
    ]
