# Generated by Django 5.1.5 on 2025-03-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("machines", "0023_machine_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="api_key",
            field=models.CharField(
                blank=True,
                help_text="API Key for authenticated when the machine accesses the API.",
                max_length=64,
                null=True,
            ),
        ),
    ]
