# Generated by Django 5.1.5 on 2025-03-01 22:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machines", "0024_machine_api_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="runtimer",
            field=models.DurationField(
                default=datetime.timedelta(0),
                help_text="Time until the machine is locked again when it is not active.",
            ),
        ),
    ]
