# Generated by Django 5.1.5 on 2025-03-18 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("machines", "0025_alter_machine_runtimer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="machine",
            options={
                "ordering": ["name"],
                "permissions": (
                    ("view_machine_state", "View Machine State"),
                    ("view_machine_logs", "View Machine Logs"),
                    ("send_machine_commands", "Send Machine Commands"),
                ),
                "verbose_name": "Machine",
                "verbose_name_plural": "Machines",
            },
        ),
    ]
