# Generated by Django 5.1.5 on 2025-05-05 19:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machines", "0026_alter_machine_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="MachineConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "primary_machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="as_primary_machine",
                        to="machines.machine",
                    ),
                ),
                (
                    "secondary_machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="as_secondary_machine",
                        to="machines.machine",
                    ),
                ),
            ],
            options={
                "verbose_name": "Machine Connection",
                "verbose_name_plural": "Machine Connections",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="MachineControlKey",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "key",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("purpose", models.CharField(max_length=100)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="control_keys",
                        to="machines.machine",
                    ),
                ),
            ],
            options={
                "verbose_name": "Control Key",
                "verbose_name_plural": "Control Keys",
                "ordering": ["-created"],
            },
        ),
    ]
