# Generated by Django 5.1.5 on 2025-05-05 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machines", "0027_machineconnection_machinecontrolkey"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="If this is a compartment in a locker, select the locker here.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="machines.machine",
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="type",
            field=models.CharField(
                choices=[
                    ("primary", "Primary"),
                    ("secondary", "Secondary"),
                    ("lock", "Lock"),
                    ("lockbox", "Multiple Locks"),
                    ("compartment", "Compartment"),
                ],
                default="primary",
                max_length=100,
            ),
        ),
    ]
