# Generated by Django 5.1.5 on 2025-05-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machines", "0028_machine_parent_alter_machine_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="machine",
            name="parent",
        ),
        migrations.AlterField(
            model_name="machine",
            name="type",
            field=models.CharField(
                choices=[
                    ("primary", "Primary"),
                    ("secondary", "Secondary"),
                    ("lock", "Lock"),
                    ("compartment", "Compartment"),
                ],
                default="primary",
                help_text="Type of machine. Primary machines are the main machines.",
                max_length=100,
            ),
        ),
    ]
