# Generated by Django 5.1.5 on 2025-05-06 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machines", "0029_remove_machine_parent_alter_machine_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="If this is a compartment in a locker, select the locker here.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="machines.machine",
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="type",
            field=models.CharField(
                choices=[
                    ("primary", "Primary"),
                    ("secondary", "Secondary"),
                    ("lock", "Lock"),
                    ("lock_group", "Locker"),
                    ("compartment", "Compartment"),
                ],
                default="primary",
                help_text="Type of machine. Primary machines are the main machines.",
                max_length=100,
            ),
        ),
    ]
