# Generated by Django 5.1.5 on 2025-05-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machines", "0030_machine_parent_alter_machine_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="hostname",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="machine",
            name="mac_address",
            field=models.CharField(blank=True, db_index=True, max_length=17, null=True),
        ),
    ]
