# Generated by Django 5.1.5 on 2025-05-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machines", "0031_alter_machine_hostname_alter_machine_mac_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="compartment_id",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
