# Generated by Django 5.1.5 on 2025-12-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machines", "0032_machine_compartment_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="state",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("maintenance", "Maintenance"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
