# Generated by Django 5.1.5 on 2025-12-04 14:04

from django.db import migrations

from machines.models import Machine as MachineModel

def migrate_is_active(apps, schema_editor):
    Machine = apps.get_model("machines", "Machine")
    for machine in Machine.objects.all():
        if machine.is_active:
            machine.state = MachineModel.MachineStatus.ACTIVE
        else:
            machine.state = MachineModel.MachineStatus.INACTIVE
        machine.save()

class Migration(migrations.Migration):

    dependencies = [
        ("machines", "0033_machine_state"),
    ]

    operations = [
        migrations.RunPython(migrate_is_active),
        migrations.RemoveField(
            model_name="machine",
            name="is_active",
        ),
    ]
