# Generated by Django 5.1.5 on 2025-12-08 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machines", "0034_remove_machine_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="machine",
            name="access_control_module",
        ),
        migrations.RemoveField(
            model_name="machine",
            name="access_control_module_settings",
        ),
        migrations.RemoveField(
            model_name="machine",
            name="actor_module",
        ),
        migrations.RemoveField(
            model_name="machine",
            name="actor_module_settings",
        ),
        migrations.RemoveField(
            model_name="machine",
            name="status_display_module",
        ),
        migrations.RemoveField(
            model_name="machine",
            name="status_display_module_settings",
        ),
        migrations.AddField(
            model_name="machine",
            name="allowed_on_holidays",
            field=models.BooleanField(
                default=True, help_text="If set, the machine can be used on holidays."
            ),
        ),
    ]
