# Generated by Django 6.0 on 2026-01-08 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_alter_location_options"),
        ("machines", "0035_remove_machine_access_control_module_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="machine",
            index=models.Index(
                fields=["mac_address"], name="machines_ma_mac_add_9ca8e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="machine",
            index=models.Index(fields=["name"], name="machines_ma_name_17437b_idx"),
        ),
    ]
