# Generated by Django 6.0.7 on 2026-08-18 13:24

import datetime
import django.db.models.deletion
import machines.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0003_alter_location_created_alter_location_description_and_more"),
        ("machines", "0036_machine_machines_ma_mac_add_9ca8e5_idx_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="machine",
            options={"ordering": ["name"], "permissions": (("view_machine_state", "View Machine State"), ("view_machine_logs", "View Machine Logs"), ("send_machine_commands", "Send Machine Commands"), ("comment_machine", "Can comment on machines")), "verbose_name": "Machine", "verbose_name_plural": "Machines"},
        ),
        migrations.AddField(
            model_name="machine",
            name="maintenance_message",
            field=models.TextField(blank=True, help_text="Reason why the machine is in maintenance mode.", null=True, verbose_name="Maintenance Message"),
        ),
        migrations.AlterField(
            model_name="machine",
            name="allowed_on_holidays",
            field=models.BooleanField(default=True, help_text="If set, the machine can be used on holidays.", verbose_name="Allowed on Holidays"),
        ),
        migrations.AlterField(
            model_name="machine",
            name="api_key",
            field=models.CharField(blank=True, help_text="API Key for authenticated when the machine accesses the API.", max_length=64, null=True, verbose_name="API Key"),
        ),
        migrations.AlterField(
            model_name="machine",
            name="chip",
            field=models.CharField(choices=[("esp32", "ESP32"), ("esp8266", "ESP8266"), ("esp32s2", "ESP32-S2"), ("esp32c3", "ESP32-C3"), ("esp32s3", "ESP32-S3")], default="esp32", max_length=100, verbose_name="Chip"),
        ),
        migrations.AlterField(
            model_name="machine",
            name="compartment_id",
            field=models.CharField(blank=True, help_text="Identifier for the compartment in a locker.", max_length=20, null=True, verbose_name="Compartment ID"),
        ),
        migrations.AlterField(
            model_name="machine",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created"),
        ),
        migrations.AlterField(
            model_name="machine",
            name="display_power_consumption",
            field=models.BooleanField(default=True, help_text="If the machine displays the power consumption when it is active.", verbose_name="Display Power Consumption"),
        ),
        migrations.AlterField(
            model_name="machine",
            name="display_time_countdown",
            field=models.BooleanField(default=True, help_text="Whether the machine displays the time remaining until it locks again when it is unlocked but not active.", verbose_name="Display Time Countdown"),
        ),
        migrations.AlterField(
            model_name="machine",
            name="encryption_key",
            field=models.CharField(blank=True, help_text="64 character encryption key for secure communication with the machine.", max_length=64, null=True, verbose_name="Encryption Key"),
        ),
        migrations.AlterField(
            model_name="machine",
            name="firmware_version",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Firmware Version"),
        ),
        migrations.AlterField(
            model_name="machine",
            name="hostname",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Hostname"),
        ),
        migrations.AlterField(
            model_name="machine",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name="IP-Address"),
        ),
        migrations.AlterField(
            model_name="machine",
            name="link_relays",
            field=models.BooleanField(default=False, help_text="If set, the machine relays are linked and the secondary relay is activated together with the primary relay.", verbose_name="Link Relays"),
        ),
        migrations.AlterField(
            model_name="machine",
            name="location",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="machines", to="locations.location", verbose_name="Location"),
        ),
        migrations.AlterField(
            model_name="machine",
            name="log_booted",
            field=models.BooleanField(default=True, help_text="Log boot events", verbose_name="Log Booted"),
        ),
        migrations.AlterField(
            model_name="machine",
            name="log_disabled",
            field=models.BooleanField(default=False, help_text="Log when machine is disabled again", verbose_name="Log Disabled"),
        ),
        migrations.AlterField(
            model_name="machine",
            name="log_enabled",
            field=models.BooleanField(default=True, help_text="Log successful unlock events", verbose_name="Log Enabled"),
        ),
        migrations.AlterField(
            model_name="machine",
            name="log_unsuccessful",
            field=models.BooleanField(default=False, help_text="Log unsuccessful unlock attempts", verbose_name="Log Unsuccessful"),
        ),
        migrations.AlterField(
            model_name="machine",
            name="mac_address",
            field=models.CharField(blank=True, db_index=True, max_length=17, null=True, verbose_name="MAC Address"),
        ),
        migrations.AlterField(
            model_name="machine",
            name="min_power",
            field=models.IntegerField(default=10, help_text="Minimum power consumption in watts for the machine to be considered active.", verbose_name="Minimum Power"),
        ),
        migrations.AlterField(
            model_name="machine",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="machine",
            name="needs_qualification",
            field=models.BooleanField(default=True, help_text="If disabled, any active user can access this machine.", verbose_name="Needs Qualification"),
        ),
        migrations.AlterField(
            model_name="machine",
            name="parent",
            field=models.ForeignKey(blank=True, help_text="If this is a compartment in a locker, select the locker here.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="children", to="machines.machine", verbose_name="Parent Machine"),
        ),
        migrations.AlterField(
            model_name="machine",
            name="runtimer",
            field=models.DurationField(default=datetime.timedelta(0), help_text="Time until the machine is locked again when it is not active.", verbose_name="Run Timer"),
        ),
        migrations.AlterField(
            model_name="machine",
            name="state",
            field=models.CharField(choices=[("active", "Active"), ("inactive", "Inactive"), ("maintenance", "Maintenance")], default="active", max_length=20, verbose_name="State"),
        ),
        migrations.AlterField(
            model_name="machine",
            name="type",
            field=models.CharField(choices=[("primary", "Primary"), ("secondary", "Secondary"), ("lock", "Lock"), ("lock_group", "Locker"), ("compartment", "Compartment")], default="primary", help_text="Type of machine. Primary machines are the main machines.", max_length=100, verbose_name="Type"),
        ),
        migrations.AlterField(
            model_name="machine",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated"),
        ),
        migrations.AlterField(
            model_name="machineconnection",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created"),
        ),
        migrations.AlterField(
            model_name="machineconnection",
            name="primary_machine",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="as_primary_machine", to="machines.machine", verbose_name="Primary Machine"),
        ),
        migrations.AlterField(
            model_name="machineconnection",
            name="secondary_machine",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="as_secondary_machine", to="machines.machine", verbose_name="Secondary Machine"),
        ),
        migrations.AlterField(
            model_name="machineconnection",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated"),
        ),
        migrations.AlterField(
            model_name="machinecontrolkey",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created"),
        ),
        migrations.AlterField(
            model_name="machinecontrolkey",
            name="key",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="Key"),
        ),
        migrations.AlterField(
            model_name="machinecontrolkey",
            name="last_used",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Last Used"),
        ),
        migrations.AlterField(
            model_name="machinecontrolkey",
            name="machine",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="control_keys", to="machines.machine", verbose_name="Machine"),
        ),
        migrations.AlterField(
            model_name="machinecontrolkey",
            name="purpose",
            field=models.CharField(max_length=100, verbose_name="Purpose"),
        ),
        migrations.AlterField(
            model_name="machinecontrolkey",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated"),
        ),
        migrations.AlterField(
            model_name="machineregistrationrequest",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created"),
        ),
        migrations.AlterField(
            model_name="machineregistrationrequest",
            name="hostname",
            field=models.CharField(max_length=100, verbose_name="Hostname"),
        ),
        migrations.AlterField(
            model_name="machineregistrationrequest",
            name="ip_address",
            field=models.GenericIPAddressField(verbose_name="IP-Address"),
        ),
        migrations.AlterField(
            model_name="machineregistrationrequest",
            name="mac_address",
            field=models.CharField(db_index=True, max_length=17, verbose_name="MAC Address"),
        ),
        migrations.AlterField(
            model_name="machineregistrationrequest",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated"),
        ),
        migrations.AlterField(
            model_name="machinetime",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created"),
        ),
        migrations.AlterField(
            model_name="machinetime",
            name="end_time",
            field=models.TimeField(verbose_name="End Time"),
        ),
        migrations.AlterField(
            model_name="machinetime",
            name="start_time",
            field=models.TimeField(verbose_name="Start Time"),
        ),
        migrations.AlterField(
            model_name="machinetime",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated"),
        ),
        migrations.AlterField(
            model_name="machinetime",
            name="weekdays",
            field=machines.models.WeekdayField(max_length=20, verbose_name="Weekdays"),
        ),
    ]
