# Generated by Django 6.0.7 on 2026-10-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0038_machine_qualification_expiry_unused_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='permission_level',
            field=models.CharField(choices=[('if_space_open', 'If Open'), ('always', 'Always'), ('never', 'Never')], default='always', help_text='When users can access this machine. Only applies if the machine does not need a qualification.', max_length=20, verbose_name='Permission Level'),
        ),
    ]
