# Generated by Django 6.1.2 on 2026-10-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machines", "0040_alter_machine_log_unsuccessful"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="encryption_key",
            field=models.CharField(blank=True, help_text="44 character encryption key for secure communication with the machine.", max_length=44, null=True, verbose_name="Encryption Key"),
        ),
    ]
