[tool.poetry]
name = "rfiding-server"
version = "1.0-beta1"
description = "Rfiding is a project to restrict access to machines and doors in our hackerspace."
authors = ["Phillip Thelen <phillip@thelen.space>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
django = "^6.0"
djangorestframework = "^3.16.1"
django-crispy-forms = "^2.5"
crispy-bootstrap5 = "^2025.6"
django-autocomplete-light = "^3.11.0"
django-auditlog = "^3.3.0"
toml = "^0.10.2"
django-webpack-loader = "^3.2.2"
channels = {extras = ["daphne"], version = "^4.3.2"}
aioesphomeapi = "^43.0.0"
celery = {extras = ["redis"], version = "^5.6.0"}
django-celery-beat = "^2.8.1"
django-celery-results = "^2.6.0"

[tool.poetry.group.dev.dependencies]
django-debug-toolbar = "^4.4.6"
freezegun = "^1.5.1"
factory-boy = "^3.3.1"
sphinx = "^8.0.2"
sphinxcontrib-httpdomain = "^1.8.1"
furo = "^2024.8.6"

[tool.poetry.group.slack.dependencies]
slack-sdk = "^3.33.2"

[tool.ruff]
target-version = "py312"

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "B", "Q"]
ignore = []
fixable = ["ALL"]

[tool.ruff.lint.per-file-ignores]
"settings.dev.py" = ["F"]
"settings.prod.py" = ["F"]
"settings.py" = ["F"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = false
docstring-code-line-length = "dynamic"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
