[tool.poetry]
name = "rfiding-server"
version = "1.2"
description = "Rfiding is a project to restrict access to machines and doors in our makerspace."
authors = ["Phillip Thelen <phillip@thelen.space>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
django = "^6.0.7"
djangorestframework = "^3.16.1"
django-crispy-forms = "^2.5"
crispy-bootstrap5 = "^2026.3"
django-autocomplete-light = "^5.0.0"
django-auditlog = "^3.4.0"
toml = "^0.10.2"
django-webpack-loader = "^3.2.2"
channels = {extras = ["daphne"], version = "^4.3.2"}
aioesphomeapi = "^45.7.0"
celery = {extras = ["redis"], version = "^5.6.0"}
django-celery-beat = { git = "https://github.com/celery/django-celery-beat.git" }
django-celery-results = "^2.6.0"

[tool.poetry.group.dev.dependencies]
django-debug-toolbar = "^7.0.0"
freezegun = "^1.5.5"
factory-boy = "^3.3.1"
sphinx = "^9.1.0"
sphinxcontrib-httpdomain = "^2.0.0"
furo = "^2025.9.25"

[tool.poetry.group.slack.dependencies]
slack-sdk = "^3.43.0"

[tool.ruff]
target-version = "py313"

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "B", "Q"]
ignore = []
fixable = ["ALL"]

[tool.ruff.lint.per-file-ignores]
"settings.dev.py" = ["F"]
"settings.prod.py" = ["F"]
"settings.py" = ["F"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = false
docstring-code-line-length = "dynamic"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
