# Generated by Django 5.0 on 2023-12-15 22:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Firmware",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("version", models.CharField(max_length=255, verbose_name="Version")),
                ("file", models.FileField(upload_to="firmware/", verbose_name="File")),
            ],
            options={
                "verbose_name": "Firmware",
                "verbose_name_plural": "Firmwares",
            },
        ),
    ]
