# Generated by Django 5.0 on 2024-01-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='type',
            field=models.CharField(choices=[('booted', 'Booted'), ('enabled', 'Enabled'), ('disabled', 'Disabled')], default='enabled', max_length=20),
            preserve_default=False,
        ),
    ]
