# Generated by Django 5.0 on 2024-01-29 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_log', '0002_accesslog_type'),
        ('tokens', '0006_alter_token_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tokens.token'),
        ),
    ]
