# Generated by Django 5.0 on 2023-12-16 00:51

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_rfidinguser_username"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="rfidinguser",
            managers=[
                ("objects", users.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="rfidinguser",
            name="name",
            field=models.CharField(blank=True, max_length=150, verbose_name="Name"),
        ),
    ]
