# Generated by Django 5.1.1 on 2024-10-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_rfidinguser_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rfidinguser",
            name="language",
            field=models.CharField(choices=[("en", "English"), ("de", "Deutsch")], default="en", max_length=10, verbose_name="Langauge"),
        ),
    ]
