# Generated by Django 5.1.1 on 2024-12-10 21:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_alter_rfidinguser_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rfidinguser",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("de", "Deutsch")],
                default="en",
                max_length=10,
                verbose_name="Langauge",
            ),
        ),
    ]
