# Generated by Django 5.1.2 on 2024-12-28 14:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_alter_rfidinguser_language"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rfidinguser",
            options={
                "ordering": ["email"],
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
    ]
