# Generated by Django 5.1.5 on 2025-03-15 21:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_userwidget"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userwidget",
            name="position",
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name="userwidget",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="widgets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userwidget",
            name="widget",
            field=models.CharField(
                choices=[
                    ("token_counts", "Token Counts"),
                    ("people_counts", "People Counts"),
                    ("machine_counts", "Machine Counts"),
                    ("access_log_latest", "Latest Access Log"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="userwidget",
            name="width",
            field=models.IntegerField(
                default=4,
                validators=[
                    django.core.validators.MinValueValidator(2),
                    django.core.validators.MaxValueValidator(12),
                ],
            ),
        ),
    ]
