# Generated by Django 5.1.5 on 2025-04-06 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_alter_userwidget_position_alter_userwidget_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rfidinguser",
            name="default_machine_filter",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("all", "All"),
                ],
                default="active",
                help_text="Default filter for the machine list",
                max_length=100,
                verbose_name="Default Machine Filter",
            ),
        ),
        migrations.AddField(
            model_name="rfidinguser",
            name="default_people_filter",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("all", "All"),
                ],
                default="active",
                help_text="Default filter for the people list",
                max_length=20,
                verbose_name="Default People Filter",
            ),
        ),
        migrations.AddField(
            model_name="rfidinguser",
            name="default_token_filter",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("all", "All"),
                    ("archived", "Archived"),
                ],
                default="active",
                help_text="Default filter for the token list",
                max_length=20,
                verbose_name="Default Token Filter",
            ),
        ),
        migrations.AlterField(
            model_name="rfidinguser",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("de", "Deutsch")],
                default="en",
                max_length=10,
                verbose_name="Language",
            ),
        ),
    ]
