# Generated by Django 5.1.5 on 2025-04-06 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_rfidinguser_default_machine_filter_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rfidinguser",
            old_name="default_machine_filter",
            new_name="default_machines_filter",
        ),
    ]
