# Generated by Django 5.1.5 on 2025-04-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0017_rename_default_machine_filter_rfidinguser_default_machines_filter",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="rfidinguser",
            name="default_machines_filter",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("all", "All"),
                ],
                default="active",
                max_length=100,
                verbose_name="Default Machine Filter",
            ),
        ),
        migrations.AlterField(
            model_name="rfidinguser",
            name="default_people_filter",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("all", "All"),
                ],
                default="active",
                max_length=20,
                verbose_name="Default People Filter",
            ),
        ),
        migrations.AlterField(
            model_name="rfidinguser",
            name="default_token_filter",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("all", "All"),
                    ("archived", "Archived"),
                ],
                default="active",
                max_length=20,
                verbose_name="Default Token Filter",
            ),
        ),
    ]
