# Generated by Django 5.1.5 on 2025-12-08 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_alter_rfidinguser_default_machines_filter_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rfidinguser",
            name="default_machines_filter",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("maintenance", "Maintenance"),
                    ("all", "All"),
                ],
                default="active",
                max_length=100,
                verbose_name="Default Machine Filter",
            ),
        ),
    ]
