# Generated by Django 6.0 on 2025-12-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_alter_rfidinguser_default_machines_filter"),
    ]

    operations = [
        migrations.AddField(
            model_name="rfidinguser",
            name="use_24h_time",
            field=models.BooleanField(
                default=True, verbose_name="Use 24-hour time format"
            ),
        ),
    ]
