# Generated by Django 6.0 on 2025-12-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_rfidinguser_use_24h_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rfidinguser",
            name="use_24h_time",
        ),
        migrations.AddField(
            model_name="rfidinguser",
            name="date_format",
            field=models.CharField(
                choices=[
                    ("locale", "Locale Default"),
                    ("dmy", "Day-Month-Year"),
                    ("mdy", "Month-Day-Year"),
                    ("ymd", "Year-Month-Day"),
                ],
                default="locale",
                max_length=10,
                verbose_name="Date format",
            ),
        ),
        migrations.AddField(
            model_name="rfidinguser",
            name="time_format",
            field=models.CharField(
                choices=[
                    ("locale", "Locale Default"),
                    ("12", "12-hour"),
                    ("24", "24-hour"),
                ],
                default="locale",
                max_length=10,
                verbose_name="Time format",
            ),
        ),
    ]
