# Generated by Django 6.0 on 2025-12-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_remove_rfidinguser_use_24h_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rfidinguser",
            name="date_format",
            field=models.CharField(
                choices=[
                    ("locale", "Locale Default"),
                    ("DMY", "Day-Month-Year (DD.MM.YYYY)"),
                    ("DMYS", "Day-Month-Year (DD.MM.YY)"),
                    ("MDY", "Month-Day-Year (MM/DD/YYYY)"),
                    ("MDYS", "Month-Day-Year (MM/DD/YY)"),
                    ("YMD", "Year-Month-Day (YYYY-MM-DD)"),
                    ("YSMD", "Year-Month-Day (YY-MM-DD)"),
                    ("WMDY", "Month Day, Year (Month DD, YYYY)"),
                    ("DWMY", "Day Month Year (DD Month YYYY)"),
                ],
                default="locale",
                max_length=10,
                verbose_name="Date format",
            ),
        ),
    ]
