# Generated by Django 6.0 on 2025-12-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0022_alter_rfidinguser_date_format"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rfidinguser",
            name="date_format",
            field=models.CharField(
                choices=[
                    ("locale", "Locale Default"),
                    ("d.m.Y", "Day-Month-Year (DD.MM.YYYY)"),
                    ("d.m.y", "Day-Month-Year (DD.MM.YY)"),
                    ("m/d/Y", "Month-Day-Year (MM/DD/YYYY)"),
                    ("m/d/y", "Month-Day-Year (MM/DD/YY)"),
                    ("Y-m-d", "Year-Month-Day (YYYY-MM-DD)"),
                    ("y-m-d", "Year-Month-Day (YY-MM-DD)"),
                    ("M d, Y", "Month Day, Year (Month DD, YYYY)"),
                    ("d M Y", "Day Month Year (DD Month YYYY)"),
                ],
                default="locale",
                max_length=10,
                verbose_name="Date format",
            ),
        ),
    ]
