# Generated by Django 4.2.1 on 2023-05-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
