# Generated by Django 5.0 on 2023-12-16 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
        ('people', '0002_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualified_people', to='machines.machine'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='people.person'),
        ),
    ]
