# Generated by Django 5.0 on 2023-12-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0004_alter_qualification_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
