# Generated by Django 5.0 on 2024-01-29 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("machines", "0004_alter_machine_options"),
        ("people", "0005_alter_person_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={
                "ordering": ["pk"],
                "verbose_name": "Person",
                "verbose_name_plural": "People",
            },
        ),
        migrations.AddField(
            model_name="qualification",
            name="instructed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instructed_qualifications",
                to="people.person",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="member_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name="Instructor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instructors",
                        to="machines.machine",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instructor",
                        to="people.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instructor",
                "verbose_name_plural": "Instructors",
            },
        ),
        migrations.AddField(
            model_name="person",
            name="can_instruct",
            field=models.ManyToManyField(
                through="people.Instructor", to="machines.machine"
            ),
        ),
    ]
