# Generated by Django 5.0.4 on 2024-09-05 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_person_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='note',
            new_name='notes',
        ),
    ]
