# Generated by Django 5.1.1 on 2024-12-10 21:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tokens", "0010_token_archived_alter_token_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlacklistedToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("serial", models.CharField(max_length=20)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
