# Generated by Django 5.1.1 on 2024-12-22 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0011_blacklistedtoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="TokenType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("label_prefix", models.CharField(blank=True, max_length=10)),
                ("label_id_padding", models.IntegerField(default=0)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Token Type",
                "verbose_name_plural": "Token Types",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="token",
            name="label_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="token",
            name="type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tokens.tokentype",
            ),
        ),
    ]
