# Generated by Django 5.1.5 on 2025-02-20 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0012_tokentype_token_label_id_token_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blacklistedtoken",
            options={
                "ordering": ["serial"],
                "verbose_name": "Blacklisted Token",
                "verbose_name_plural": "Blacklisted Tokens",
            },
        ),
        migrations.AlterModelOptions(
            name="unknowntoken",
            options={
                "ordering": ["serial"],
                "verbose_name": "Unknown Token",
                "verbose_name_plural": "Unknown Tokens",
            },
        ),
    ]
