# Generated by Django 5.1.5 on 2025-02-24 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0013_alter_blacklistedtoken_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="token",
            options={
                "ordering": ["serial"],
                "verbose_name": "Token",
                "verbose_name_plural": "Tokens",
            },
        ),
        migrations.AlterModelOptions(
            name="unknowntoken",
            options={
                "ordering": ["-created"],
                "verbose_name": "Unknown Token",
                "verbose_name_plural": "Unknown Tokens",
            },
        ),
    ]
