# Generated by Django 6.0 on 2026-01-08 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0016_person_people_pers_name_3035d1_idx"),
        ("tokens", "0014_alter_token_options_alter_unknowntoken_options"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="token",
            index=models.Index(fields=["serial"], name="tokens_toke_serial_ec627d_idx"),
        ),
    ]
