# Generated by Django 6.0.7 on 2026-08-18 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machines", "0037_alter_machine_options_machine_maintenance_message_and_more"),
        ("people", "0017_alter_person_options_alter_person_created_and_more"),
        ("tokens", "0015_token_tokens_toke_serial_ec627d_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blacklistedtoken",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created"),
        ),
        migrations.AlterField(
            model_name="blacklistedtoken",
            name="serial",
            field=models.CharField(max_length=20, verbose_name="Serial"),
        ),
        migrations.AlterField(
            model_name="blacklistedtoken",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated"),
        ),
        migrations.AlterField(
            model_name="token",
            name="archived",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Archived"),
        ),
        migrations.AlterField(
            model_name="token",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created"),
        ),
        migrations.AlterField(
            model_name="token",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active"),
        ),
        migrations.AlterField(
            model_name="token",
            name="label_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="Label ID"),
        ),
        migrations.AlterField(
            model_name="token",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="token",
            name="person",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="people.person", verbose_name="Person"),
        ),
        migrations.AlterField(
            model_name="token",
            name="purpose",
            field=models.CharField(max_length=100, verbose_name="Purpose"),
        ),
        migrations.AlterField(
            model_name="token",
            name="serial",
            field=models.CharField(db_index=True, max_length=20, verbose_name="Serial"),
        ),
        migrations.AlterField(
            model_name="token",
            name="type",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="tokens.tokentype", verbose_name="Type"),
        ),
        migrations.AlterField(
            model_name="token",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated"),
        ),
        migrations.AlterField(
            model_name="tokentype",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created"),
        ),
        migrations.AlterField(
            model_name="tokentype",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="tokentype",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active"),
        ),
        migrations.AlterField(
            model_name="tokentype",
            name="label_id_padding",
            field=models.IntegerField(default=0, verbose_name="Label ID Padding"),
        ),
        migrations.AlterField(
            model_name="tokentype",
            name="label_prefix",
            field=models.CharField(blank=True, max_length=10, verbose_name="Label Prefix"),
        ),
        migrations.AlterField(
            model_name="tokentype",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="tokentype",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated"),
        ),
        migrations.AlterField(
            model_name="unknowntoken",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created"),
        ),
        migrations.AlterField(
            model_name="unknowntoken",
            name="machine",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="machines.machine", verbose_name="Machine"),
        ),
        migrations.AlterField(
            model_name="unknowntoken",
            name="serial",
            field=models.CharField(max_length=20, verbose_name="Serial"),
        ),
        migrations.AlterField(
            model_name="unknowntoken",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated"),
        ),
    ]
