# Generated by Django 4.2.10 on 2024-04-20 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spacestate',
            options={'ordering': ['-created']},
        ),
    ]
