# Generated by Django 5.0.4 on 2024-09-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0008_qualification_permission_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
