# Generated by Django 5.1.1 on 2024-12-10 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0010_rename_note_person_notes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="instructor",
            options={
                "ordering": ["machine", "person"],
                "verbose_name": "Instructor",
                "verbose_name_plural": "Instructors",
            },
        ),
        migrations.AlterModelOptions(
            name="person",
            options={
                "ordering": ["member_id"],
                "permissions": (("change_instructor", "Can manage instructors"),),
                "verbose_name": "Person",
                "verbose_name_plural": "People",
            },
        ),
        migrations.AlterModelOptions(
            name="qualification",
            options={
                "ordering": ["machine", "person__name"],
                "permissions": (("qualify_person", "Can manage qualifications"),),
                "verbose_name": "Qualification",
                "verbose_name_plural": "Qualifications",
            },
        ),
    ]
