# Generated by Django 5.1.5 on 2025-12-03 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0011_alter_instructor_options_alter_person_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="qualification",
            name="is_instructor",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="qualification",
            name="is_maintainer",
            field=models.BooleanField(default=False),
        ),
    ]
