# Generated by Django 5.1.5 on 2025-12-03 19:14

from django.db import migrations

def migrate_instructors(apps, schema_editor):
    Instructor = apps.get_model("people", "Instructor")
    Qualification = apps.get_model("people", "Qualification")
    for instructor in Instructor.objects.all():
        for quali in Qualification.objects.filter(person=instructor.person, machine=instructor.machine):
            quali.is_instructor = True
            quali.save()

class Migration(migrations.Migration):

    dependencies = [
        ("people", "0012_qualification_is_instructor_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_instructors),
        migrations.DeleteModel(
            name="Instructor",
        ),
    ]
