# Generated by Django 5.1.5 on 2025-12-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0013_auto_20251203_1914"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qualification",
            name="is_instructor",
            field=models.BooleanField(
                default=False,
                help_text="Instructors can give safety briefings and qualify other people on this machine.",
            ),
        ),
        migrations.AlterField(
            model_name="qualification",
            name="is_maintainer",
            field=models.BooleanField(
                default=False,
                help_text="Maintainers can perform maintenance on this machine and activate it in maintenance state.",
            ),
        ),
    ]
