# Generated by Django 5.1.5 on 2025-12-08 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0014_alter_qualification_is_instructor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="is_system_maintainer",
            field=models.BooleanField(
                default=False,
                help_text="System maintainers have access to all machines in maintenance mode.",
            ),
        ),
    ]
