# Generated by Django 6.0 on 2026-01-08 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0015_person_is_system_maintainer"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="person",
            index=models.Index(fields=["name"], name="people_pers_name_3035d1_idx"),
        ),
    ]
