# Generated by Django 6.0.7 on 2026-08-18 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machines", "0037_alter_machine_options_machine_maintenance_message_and_more"),
        ("people", "0016_person_people_pers_name_3035d1_idx"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={"ordering": ["member_id"], "permissions": (("change_instructor", "Can manage instructors"), ("comment_person", "Can comment on people")), "verbose_name": "Person", "verbose_name_plural": "People"},
        ),
        migrations.AlterField(
            model_name="person",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created"),
        ),
        migrations.AlterField(
            model_name="person",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="Email address"),
        ),
        migrations.AlterField(
            model_name="person",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active"),
        ),
        migrations.AlterField(
            model_name="person",
            name="is_system_maintainer",
            field=models.BooleanField(default=False, help_text="System maintainers have access to all machines in maintenance mode.", verbose_name="Is System Maintainer"),
        ),
        migrations.AlterField(
            model_name="person",
            name="member_id",
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name="Member ID"),
        ),
        migrations.AlterField(
            model_name="person",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="person",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="person",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated"),
        ),
        migrations.AlterField(
            model_name="qualification",
            name="comment",
            field=models.TextField(blank=True, null=True, verbose_name="Comment"),
        ),
        migrations.AlterField(
            model_name="qualification",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created"),
        ),
        migrations.AlterField(
            model_name="qualification",
            name="instructed_by",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="instructed_qualifications", to="people.person", verbose_name="Instructed By"),
        ),
        migrations.AlterField(
            model_name="qualification",
            name="is_instructor",
            field=models.BooleanField(default=False, help_text="Instructors can give safety briefings and qualify other people on this machine.", verbose_name="Is Instructor"),
        ),
        migrations.AlterField(
            model_name="qualification",
            name="is_maintainer",
            field=models.BooleanField(default=False, help_text="Maintainers can perform maintenance on this machine and activate it in maintenance state.", verbose_name="Is Maintainer"),
        ),
        migrations.AlterField(
            model_name="qualification",
            name="machine",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="qualified_people", to="machines.machine", verbose_name="Machine"),
        ),
        migrations.AlterField(
            model_name="qualification",
            name="permission_level",
            field=models.CharField(choices=[("if_space_open", "If space is open"), ("always", "Always"), ("never", "Never")], default="if_space_open", max_length=20, verbose_name="Permission Level"),
        ),
        migrations.AlterField(
            model_name="qualification",
            name="person",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="qualifications", to="people.person", verbose_name="Person"),
        ),
        migrations.AlterField(
            model_name="qualification",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated"),
        ),
    ]
