# Generated by Django 6.0.7 on 2026-08-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0017_alter_person_options_alter_person_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="qualification",
            name="expired",
            field=models.DateTimeField(blank=True, help_text="When this qualification expired.", null=True, verbose_name="Expired"),
        ),
        migrations.AddField(
            model_name="qualification",
            name="expires_at",
            field=models.DateTimeField(blank=True, help_text="When this qualification will expire if it is not used again. Empty if expiration is disabled for this machine.", null=True, verbose_name="Expires At"),
        ),
        migrations.AddField(
            model_name="qualification",
            name="last_used",
            field=models.DateTimeField(blank=True, help_text="When this qualification was last used to access the machine.", null=True, verbose_name="Last Used"),
        ),
        migrations.AlterField(
            model_name="qualification",
            name="permission_level",
            field=models.CharField(choices=[("if_space_open", "Space is open"), ("always", "Always"), ("never", "Never")], default="if_space_open", max_length=20, verbose_name="Permission Level"),
        ),
    ]
