# Generated by Django 6.0.7 on 2026-08-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0019_qualification_notified_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="language",
            field=models.CharField(choices=[("en", "English"), ("de", "Deutsch")], default="en", help_text="Preferred language for notifications and emails.", max_length=10, verbose_name="Language"),
        ),
        migrations.AddField(
            model_name="person",
            name="slack_conversation_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name="Slack conversation ID"),
        ),
        migrations.AddField(
            model_name="person",
            name="slack_email",
            field=models.CharField(blank=True, help_text="Slack account e-mail for sending notifications.", max_length=100, null=True, unique=True, verbose_name="Slack e-mail"),
        ),
        migrations.AlterField(
            model_name="person",
            name="email",
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name="E-Mail address"),
        ),
    ]
