# Generated by Django 5.0 on 2024-01-29 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0005_rename_user_token_person'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='token',
            options={'ordering': ['pk'], 'verbose_name': 'Token', 'verbose_name_plural': 'Tokens'},
        ),
    ]
