# Generated by Django 5.0.4 on 2024-09-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0007_alter_token_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
